### PR TITLE
Add Rank Changer And other changes

### PR DESCRIPTION
**Pull request by Kinako7285**
This is my first time using this feature, so I'm worried if I can make a normal pull request.
Please let me know if you make a mistake.
I made a pull request again because it contained the wrong file.

### CODE REVIEW

**Comment by derole1** [comment]
Apologies for the delay in response. I appreciate the work done here, however have a few things id like to mention before merging.

Firstly all the message boxes have been translated into Japanese, whilst I understand that its helpful for you its primarily an English application, perhaps we could update the translation database to be able to accommodate for message boxes and integrate it into that?

In terms of merging a rank editor, I've never really been a fan of it or seen a reason to need to edit it, the goal of the project is mainly to apply dress up parts. However from testing all seems to work properly, so ill consider if it should be merged over the next few days.

I'd appreciate if the Japanese messages could be integrated into the translation database so everything's a bit more consistent :D, I'll leave the pull request open for now.

**Comment by Kinako7285** [comment]
This probably completes the fix.
Verification please.

**Comment by derole1** [comment]
> This probably completes the fix.
> Verification please.

Thank you, I will verify this tomorrow

**Comment by derole1** [comment]
Everything looks ok, ill merge, please report if there's any issues

**Pull request merged**
